### ISSUE TITLE
secure connection error

### ISSUE THREAD

**Issue by BOBODDO** [vgiselbrecht/chat-server#3]
Hello developer, thank you as always.

The following problem occurred while using the chat server, and we report the issue.

In the nginx environment where https secure access is implemented, there is a problem that the browser blocks the access because https is not used between the chat client and the chat server.

That is, if 'https://chat.gise.at' is the chat client shown to the client, and 'https://signaling.chat.gise.at' is the address of the chat server, the chat client uses the http protocol instead of https protocol to connect to the chat server.

I know you are busy, but please check.
thank you as always.

**Comment by vgiselbrecht** [comment]
Hey BOBODDO,

it should work, if you add the host as **wss**://signaling.chat.gise.at/.

Regards Valentin

**Comment by BOBODDO** [comment]
Sincerely Thanks!
